backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "post"
    label: "Aktualności"
    folder: "src/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }